[gh_runner]
192.168.2.101 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519

[vpn_server]
3.104.200.207 ansible_user=ubuntu ansible_port=2222 ansible_ssh_private_key_file=~/.ssh/wireguard-key

[proxmox]
192.168.2.70 ansible_user=ben ansible_become_pass=3719
